-- ============================================
-- My Chat App - Supabase Schema Setup
-- Run this in the Supabase SQL Editor
-- ============================================

-- 1. Profiles table (extends the auth.users table)
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique not null,
  email text unique not null,
  created_at timestamptz default now()
);

-- 2. Messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  receiver_id uuid not null references public.profiles (id) on delete cascade,
  message text not null,
  created_at timestamptz default now()
);

create index if not exists messages_conversation_idx
  on public.messages (sender_id, receiver_id, created_at);

-- 3. Auto-create a profile row for newly registered users
--    Username is stored in auth.users raw_user_meta_data -> 'username'
create or replace function public.handle_new_user()
returns trigger
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$ language plpgsql;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================
-- Row Level Security Policies
-- ============================================
alter table public.profiles enable row level security;
alter table public.messages enable row level security;

-- Profiles: anyone can read all profiles (needed for search),
-- but a user can only update their own.
create policy "Profiles are viewable by all"
  on public.profiles for select
  using (true);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Messages: users can only read messages where they are sender or receiver.
create policy "Users can read their own conversations"
  on public.messages for select
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- Messages: users can only insert messages sent as themselves.
create policy "Users can send messages as themselves"
  on public.messages for insert
  with check (auth.uid() = sender_id);

-- Messages: users can only delete their own messages.
create policy "Users can delete their own messages"
  on public.messages for delete
  using (auth.uid() = sender_id);

-- ============================================
-- Realtime
-- ============================================
-- Enable realtime for the messages table.
alter publication supabase_realtime add table public.messages;
